apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: legacyapp
  namespace: argocd
spec:
  project: portfolio
  source:
    repoURL: 'https://github.com/imtarget05/Productionized-LegacyApp.git'
    path: 'infrastructure/kubernetes/overlays/prod'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: legacyapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m