apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: flashsale
type: Opaque
stringData:
  host: "amqp://admin:admin123@rabbitmq.messaging.svc.cluster.local:5672/"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: flashsale
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-secret
    key: host
